apiVersion: v1
kind: Service
metadata:
  name: subhamipl123-service
spec:
  selector:
    app: subhamipl123
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subhamipl123
spec:
  selector:
    matchLabels:
      app: subhamipl123
  replicas: 4
  template:
    metadata:
      labels:
        app: subhamipl123
    spec:
      containers:
      - name: subhamipl123
        image: subhamipl123:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
